services:
  app:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    env_file:
      - .env.compose
    container_name: swift-api-service
    ports:
      - 8080:8080
    command: ["serve", "--env", "local", "--hostname", "0.0.0.0", "--port", "8080"]
